### PR TITLE
Emit language-specific relationships

### PR DESCRIPTION
**Pull request by franklinsch**
Bug/issue #, if applicable: rdar://91627374

## Summary

Use SymbolKit's new `relationshipsByLanguage` API to emit language-specific relationships, e.g., for symbols that have different conformances in Swift vs. Objective-C.

## Dependencies

https://github.com/apple/swift-docc-symbolkit/pull/28

## Testing

Build documentation for the following class:

```
@interface MyClass : NSObject
@end
```

Verify that on the Swift documentation page, the relationships listed include the ones synthesized by the Swift compiler, e.g., a conformance to `Swift.Equatable`, and that on the Objective-C page, only `NSObject` is listed as an Inherited From symbol.

## Checklist

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

## TODO

- [x] Add tests for language-specific `defaultImplementationOf`, `requirementOf`, and `optionalRequirementOf` relationships

### CODE REVIEW

**Comment by franklinsch** [comment]
Yep!

**Review by QuietMisdreavus — APPROVED** [review]
Looks good, pending any other needed changes in the swift-markdown PR.

**Comment by franklinsch** [comment]
https://github.com/apple/swift-docc-symbolkit/pull/28

@swift-ci please test

**Comment by franklinsch** [comment]
Testing passed here with the SymbolKit change: https://github.com/apple/swift/pull/59524

**Pull request merged**
