### PR TITLE
SwiftDocC: implement mime type sniffing for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Windows can support the mime type sniffing via URL Monikers (similar to how Darwin can use UTI).  This requires a newer toolchain as it requires a modified WinSDK module.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
> This requires a newer toolchain as it requires a modified WinSDK module.

What does this mean for this PR? Is there a `canImport` check we can use here or is WinSDK available in older toolchains but we need a newer version?

**Comment by compnerd** [comment]
> > This requires a newer toolchain as it requires a modified WinSDK module.
> 
> What does this mean for this PR? Is there a `canImport` check we can use here or is WinSDK available in older toolchains but we need a newer version?

Correct, `WinSDK` has been available since pretty much day 1.  We would need a newer toolchain (I think that 7/23 or 8/3 snapshots should be new enough).

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
> We would need a newer toolchain (I think that 7/23 or 8/3 snapshots should be new enough).

Ok. But if that's already available in recent toolchains then that shouldn't be a concern since DocC also gets submitted to the toolchain.

**Review by d-ronnqvist — APPROVED** [review]

**Pull request merged**
