### PR TITLE
Remove errors that are never raised anywhere.

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: 

## Summary

This removes defined error types that are never used anywhere. None of these were public API so removing them won't cause any breaking changes.

## Dependencies

None.

## Testing

Build DocC. There shouldn't be any compiler errors.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- ~[ ] Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Review by patshaughnessy — CHANGES_REQUESTED** [review]
I took a few minutes to double check... looks like you forgot one unused error in RenderNodeVariantOverridesApplier.swift:

```
    /// An error that occured while applying overrides in a render node.
    public enum Error: DescribedError {
        /// An error indicating that the error node is corrupted or malformed.
        case corruptedRenderNode
        
        public var errorDescription: String {
            switch self {
            case .corruptedRenderNode:
                return "Corrupted or malformed render node value."
            }
        }
    }
```

**Comment by d-ronnqvist** [comment]
> I took a few minutes to double check... looks like you forgot one unused error in RenderNodeVariantOverridesApplier.swift:
> 
> ```
>     /// An error that occured while applying overrides in a render node.
>     public enum Error: DescribedError {
>         /// An error indicating that the error node is corrupted or malformed.
>         case corruptedRenderNode
>         
>         public var errorDescription: String {
>             switch self {
>             case .corruptedRenderNode:
>                 return "Corrupted or malformed render node value."
>             }
>         }
>     }
> ```

That error is public so it would be source breaking to just remove it but I can mark it as deprecated to be removed in a future release.

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
