### PR TITLE
Convert symbol graph dictionary structures

### PR DESCRIPTION
**Pull request by franklinsch**
Bug/issue #, if applicable: rdar://101407961

## Summary

I've been experimenting with supporting REST API documentation. This PR adopts the SymbolKit models from https://github.com/apple/swift-docc-symbolkit/pull/53 and converts them to render JSON.

## Dependencies

https://github.com/apple/swift-docc-symbolkit/pull/53

## Testing

Build documentation for symbol graph files that contain `dictionary` and `dictionaryKey` structures and verify that they appear in the generated documentation.

## Checklist

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Review by QuietMisdreavus — APPROVED** [review]
Looks good, some non-blocking comments.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@swift-ci please test

**Pull request merged**
