### PR TITLE
[5.8] Autogenerate directive documentation based on models in SwiftDocC framework

### PR DESCRIPTION
**Pull request by ethan-kusters**
- **Explanation**: Adds support for autogenerating Swift-DocC's directive documentation based on the in-framework models.
- **Scope**: Scope is small – limited to documentation generation that occurs on-demand by running a separate script.
- **Issue**: rdar://103925835
- **Risk**: Low. Very little framework code is affected here.
- **Testing**: Tested for API breakage and the documentation is produced as expected: https://ethan-kusters.github.io/swift-docc/documentation/docc
- Original PR: https://github.com/apple/swift-docc/pull/447
- **Reviewer**: @daniel-grumberg

### CODE REVIEW

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
@swift-ci please test macOS platform

**Review by franklinsch — APPROVED** [review]

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
@swift-ci please test macOS platform

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Pull request merged**
