### PR TITLE
Add initial support for documenting HTTP/REST requests

### PR DESCRIPTION
**Pull request by franklinsch**
Bug/issue #, if applicable:

rdar://101408429
rdar://101409112
rdar://101408868
rdar://101408667

## Summary

Adds initial support for parsing HTTP/REST structures defined in https://github.com/apple/swift-docc-symbolkit/pull/54.

## Dependencies

https://github.com/apple/swift-docc-symbolkit/pull/54

## Testing

Generate documentation for a documentation catalog that contains symbol graphs that define HTTP endpoints, and verify that the corresponding website pages are generated.

## Checklist

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@swift-ci please test

**Review by QuietMisdreavus — APPROVED** [review]
Looks good, thanks!

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
