### PR TITLE
Support resolving links in `@DeprecationSummary` content

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: rdar://120374614

## Summary

This adds support for resolving links in a symbol's `@DeprecationSummary` content. 

Previously the `ReferenceResolver` didn't visit a symbol's `deprecatedSummaryVariants` so any link in that content didn't resolve but also didn't warn about the links being unresolved.

## Dependencies

None

## Testing

In a documentation catalog with any symbol, add documentation extension file with a `@DeprecationSummary` directive that has a link in its content.

Build and preview the documentation. The deprecation summary should link to the other page.

Replace the link with something that won't resolve—for example ` ``NotFound`` `—and rebuild the documentation. There should be a warning about the unresolved link.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- ~[ ] Updated documentation if necessary~

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by sofiaromorales** [comment]
@d-ronnqvist do you know if there's any reason why `@DeprecationSummary` is not listed as a directive in the DocC docs? https://www.swift.org/documentation/docc

**Review by sofiaromorales — APPROVED** [review]

**Comment by sofiaromorales** [comment]
> > @d-ronnqvist do you know if there's any reason why `@DeprecationSummary` is not listed as a directive in the DocC docs? https://www.swift.org/documentation/docc
> 
> I don't think there's a reason. Why probably my just forgot to list it.

can we add it as part of this pr?

**Comment by d-ronnqvist** [comment]
> > > @d-ronnqvist do you know if there's any reason why `@DeprecationSummary` is not listed as a directive in the DocC docs? https://www.swift.org/documentation/docc
> > 
> > 
> > I don't think there's a reason. Why probably my just forgot to list it.
> 
> can we add it as part of this pr?

I found that we do intentionally [hide it from the documentation][1] but I don't know why.

[1]: https://github.com/apple/swift-docc/blob/main/Sources/SwiftDocC/Semantics/Symbol/DeprecationSummary.swift#L31

**Pull request merged**
