### PR TITLE
Allow `readOnly` attribute in `TypedProperty` OpenAPI spec

### PR DESCRIPTION
**Pull request by mportiz08**
Bug/issue #, if applicable: 91505904

## Summary

This adds support for a new `readOnly` boolean attribute as an optional property of the `TypedProperty` schema.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] ~~Added tests~~, documentation only change
- [X] Ran the `./bin/test` script and it succeeded
- [X] Updated documentation if necessary

### CODE REVIEW

**Comment by mportiz08** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
LGTM

**Comment by franklinsch** [comment]
Should we also add this to the Swift model? Otherwise, if DocC decodes an object with this property, then encodes again, the property will be lost.

**Comment by mportiz08** [comment]
> Should we also add this to the Swift model? Otherwise, if DocC decodes an object with this property, then encodes again, the property will be lost.

Updated: https://github.com/apple/swift-docc/pull/134/commits/dc67bd581b1211203c2f899c8f58bdc480893a44

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by franklinsch** [comment]
@mportiz08 Can we also add a test for this to verify that the encoding and decoding happens correctly? There are existing tests in `PlistSymbolTests`.

**Comment by franklinsch** [comment]
@mportiz08 Can we also add a test for this to verify that the encoding and decoding happens correctly? There are existing tests in `PlistSymbolTests`.

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
> @mportiz08 Can we also add a test for this to verify that the encoding and decoding happens correctly? There are existing tests in `PlistSymbolTests`.

Yep, [added](https://github.com/apple/swift-docc/pull/134/commits/ce33d2d718d885ac50aacb98eae4165a7aea2282)

Sorry, I had meant to do that but couldn't find the appropriate tests to update before—found them now.

**Review by franklinsch — APPROVED** [review]
Looks great, thanks!

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
