### PR TITLE
Add documentation for the DisplayName directive

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: 

## Summary

This adds documentation for the `@DisplayName` directive.
 
## Dependencies

n/a

## Testing

- Generate an updated directive symbol graph
```
swift run generate-symbol-graph
```
- Preview the DocCDocumentation documentation
```
swift run docc preview Sources/DocCDocumentation/DocCDocumentation.docc
```

The DisplayName directive should be documented as a child of the Metadata directive.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] ~Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
Should I also commit the updated `Sources/DocCDocumentation/DocCDocumentation.docc/DocC.symbols.json` file?

**Comment by ethan-kusters** [comment]
> Should I also commit the updated `Sources/DocCDocumentation/DocCDocumentation.docc/DocC.symbols.json` file?

Yes please! We don't currently have automation for that.

**Comment by ktoso** [comment]
Oh great -- just came over to request this feature actually 😄 👍 Thanks!

**Review by franklinsch — APPROVED** [review]
Thank you for this (and for implementing this awesome feature!)

**Comment by franklinsch** [comment]
@d-ronnqvist Shall we merge this?

**Comment by d-ronnqvist** [comment]
I have some additional improvements to the docs that I can push and then we can merge this.

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
