### PR TITLE
[NFC] Optimus some unchangeable member to be "let" instead of "var"

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

## Summary

Optimus some unchangeable member to be "let" instead of "var"

## Dependencies

None

## Testing

Non-Functional Change

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Ran the `./bin/test` script and it succeeded

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
> My take on this is that since these types are structs, mutability is already controlled by the client, and making their properties `var`s helps clients manipulate/re-assign these values (especially useful when writing unit tests, for example).

Yes, I agree on this. But I think the default behavior should be minimal permission which is  "private" and "let" unless we have a solid reason to do it. That is said, if we someday later find some member really needs to be modified, we can then change it to "var"(Just like what we do to remove "private" sometimes).

Moreover there is something like "@testable import and spi" in swift to better constraint the access control model (Making it accessible in test or other module without making it totally public or open).

I was wondering if there is something similar in get/set model. Currently we only have "private(set)" which seems not flexible enough in some cases. Is there a grammar which allows to "set" in test module or on specific clients in swift?(Like testableSet or something)

**Comment by Kyle-Ye** [comment]
Although currently there is no code in swift-docc modify those members. But other package which depends on swift-docc may use them and potentially modify them in their existing codebase since those members are public.

So this should be a source breaking change 😂

Did not know if you are worried about this?

**Comment by franklinsch** [comment]
To maintain compatibility with existing clients, we'd deprecate the setter of the property and remove it down the line. Since we do expect clients to import the `SwiftDocC` library directly (e.g., IDE projects), I do think the added flexibility of keeping these as `var`s helps. 

Making the property `internal(set)` would still allow Swift-DocC's tests to mutate those properties (via `@testable import SwiftDocC`), but I believe there are valid cases beyond testing where flexibility would be beneficial for clients. Another idea is to use the `@_spi` annotation to prevent access to clients by default, but I think that would be an over-complication and not valuable in this case.

Once reason for making these `let`s would be if it would allow clients to set a value that violates a precondition enforced by the implementation of the type. For example, if we had:
```swift
public struct SourceLanguage: Hashable, Coddle {
  public var name: String

  public init(name: String) {
    precondition(!name.isEmpty)
    self.name = name
  }

  public var firstCharacterOfName: Character {
    name.first!
  } 
}
```
in that case we wouldn't make to make it a `var` because the client would be able to set `name` to an empty string and cause a crash in the computed property.

**Comment by Kyle-Ye** [comment]
> To maintain compatibility with existing clients, we'd deprecate the setter of the property and remove it down the line. Since we do expect clients to import the `SwiftDocC` library directly (e.g., IDE projects), I do think the added flexibility of keeping these as `var`s helps.
> 
> Making the property `internal(set)` would still allow Swift-DocC's tests to mutate those properties (via `@testable import SwiftDocC`), but I believe there are valid cases beyond testing where flexibility would be beneficial for clients. Another idea is to use the `@_spi` annotation to prevent access to clients by default, but I think that would be an over-complication and not valuable in this case.
> 
> Once reason for making these `let`s would be if it would allow clients to set a value that violates a precondition enforced by the implementation of the type. For example, if we had:
> 
> ```swift
> public struct SourceLanguage: Hashable, Coddle {
>   public var name: String
> 
>   public init(name: String) {
>     precondition(!name.isEmpty)
>     self.name = name
>   }
> 
>   public var firstCharacterOfName: Character {
>     name.first!
>   } 
> }
> ```
> 
> in that case we wouldn't make to make it a `var` because the client would be able to set `name` to an empty string and cause a crash in the computed property.

I'm very sorry if I get you wrong. Still did not know your conclusion.

So your opinion is not change the code or suggest that we should change from `public var xx` to `public internal(set) var xx`?

**Comment by franklinsch** [comment]
Sorry about that, I should have made it clearer. I think we should keep the code as-is (`public var xxx`) for added flexibility.

**Comment by Kyle-Ye** [comment]
Got it.

**Pull request closed without merging**
