### PR TITLE
enable Doxygen support by default

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Bug/issue #, if applicable: rdar://107002535

## Summary

This PR turns on the Doxygen support added in https://github.com/apple/swift-docc/pull/497 for all doc builds.

## Dependencies

None

## Testing

See test instructions in https://github.com/apple/swift-docc/pull/497. Also ensure that existing functionality is not impacted.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ n/a ] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ n/a ] Updated documentation if necessary

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by d-ronnqvist** [comment]
Should it still be possible to disable the Doxygen support by passing `--no-experimental-parse-doxygen-commands`?

**Comment by QuietMisdreavus** [comment]
@d-ronnqvist I thought about allowing it, but decided against it. I can see how it would be useful for debugging; i'll try to work it in.

**Comment by ethan-kusters** [comment]
> Should it still be possible to disable the Doxygen support by passing `--no-experimental-parse-doxygen-commands`?

I don't think this should be possible at this level actually. At some point we might want to add support for different parsing modes (disabling legacy Swift callout support and Doxygen support for example) but I would view that as a separate feature and not something we would do through the global `Features` struct.

**Review by ethan-kusters — APPROVED** [review]

**Review by d-ronnqvist — APPROVED** [review]

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
