### PR TITLE
[5.6] Add Static Hosting Support

### PR DESCRIPTION
**Pull request by ethan-kusters**
- **Rationale:** Adds support for creating DocC archives that are compatible with static hosting environments like GitHub Pages.
- **Risk:** Low.
- **Risk Detail:** This is an isolated change that touches very little existing DocC code. 
- **Reward:** High
- **Reward Details:** Enables new hosting scenarios for users of DocC.
- **Original PR:** #44
- **Issue:** rdar://70800606
- **Code Reviewed By:** Ethan Kusters
- **Testing Details:** New tests covering changes have been added. Existing tests continue to pass.

### CODE REVIEW

**Comment by ethan-kusters** [comment]
I've cherry-picked @d-ronnqvist's fix for a test case in the original PR as we should only land these changes together.

#57

**Review by franklinsch — APPROVED** [review]

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by iltercengiz** [comment]
@ethan-kusters awesome to see this is merged into release. I've been trying to manually use DocC and renderer to setup our project's documentation to be hosted with GitHub pages but having trouble with the paths (`--hosting-base-path` to be precise). Any plans for sharing steps to follow if we want to utilize static hosting today?

**Comment by mportiz08** [comment]
> @ethan-kusters awesome to see this is merged into release. I've been trying to manually use DocC and renderer to setup our project's documentation to be hosted with GitHub pages but having trouble with the paths (`--hosting-base-path` to be precise). Any plans for sharing steps to follow if we want to utilize static hosting today?

@ iltercengiz You may want to check out the forums [post](https://forums.swift.org/t/support-hosting-docc-archives-in-static-hosting-environments/53572) if you haven't already, which has example command line invocations.

**Comment by ethan-kusters** [comment]
> > @ethan-kusters awesome to see this is merged into release. I've been trying to manually use DocC and renderer to setup our project's documentation to be hosted with GitHub pages but having trouble with the paths (`--hosting-base-path` to be precise). Any plans for sharing steps to follow if we want to utilize static hosting today?
> 
> @iltercengiz You may want to check out the forums [post](https://forums.swift.org/t/support-hosting-docc-archives-in-static-hosting-environments/53572) if you haven't already, which has example command line invocations.

Hi @iltercengiz! Sorry- I missed this entirely. As @mportiz08 mentioned, the forums post is a good place to start. I'll plan on updating the thread this week with more concrete instructions now that we have an OSS toolchain that includes support for this.

Alternatively, if you're interested, you could consider using the Swift-DocC-Plugin which should simplify things here. Here's the announcement post for the plugin: https://forums.swift.org/t/swift-docc-plugin-for-swiftpm/54725. And here's the specific docs on how to generate GitHub pages compatible documentation: https://apple.github.io/swift-docc-plugin/documentation/swiftdoccplugin/publishing-to-github-pages.

**Pull request merged**
