### PR TITLE
Update test data to fit the swift-markdown

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

See more info on apple/swift-markdown#49

## Summary

Split the unlated change on #278 about swift-markdown

## Dependencies

apple/swift-markdown#50

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
apple/swift-markdown#50
@swift-ci please smoke test

**Comment by Kyle-Ye** [comment]
apple/swift-markdown#50
@swift-ci please test

**Comment by franklinsch** [comment]
@Kyle-Ye it doesn't seem like cross-repo testing is working in this repo:

```
Creating working copy for https://github.com/apple/swift-markdown.git
Working copy of https://github.com/apple/swift-markdown.git resolved at main
```

You can trigger cross-repo testing in the Swift repository, and trigger testing using the `please test` command.

**Comment by Kyle-Ye** [comment]
https://github.com/apple/swift-markdown/pull/50

@swift-ci please test

**Comment by Kyle-Ye** [comment]
> @Kyle-Ye it doesn't seem like cross-repo testing is working in this repo:
> 
> ```
> Creating working copy for https://github.com/apple/swift-markdown.git
> Working copy of https://github.com/apple/swift-markdown.git resolved at main
> ```
> 
> You can trigger cross-repo testing in the Swift repository, and trigger testing using the `please test` command.

Looks like the cross-repo testing is OK. See https://github.com/apple/swift/pull/59427

But how can we pass the tests on this PR? (Merge the markdown PR first and then run the test and merge this PR? This will cost some time and during it, the pipeline will break)

**Comment by Kyle-Ye** [comment]
> Cross-repo testing isn't available in this repo, so I'll use my administrator access to merge this assuming testing passed in the Swift repo. However, we should trigger regular tests (`@swift-ci please test`) because smoke testing doesn't include running Swift-DocC tests.

Got it.

**Review by franklinsch — APPROVED** [review]

**Comment by franklinsch** [comment]
@Kyle-Ye The tests passed in the Swift repo. Are you good with me merging this PR and https://github.com/apple/swift-markdown/pull/50#pullrequestreview-1007157364?

**Comment by Kyle-Ye** [comment]
Of course. Please merge them together. And I think they are not fit into the release of swift-5.7.

**Pull request merged**
