### PR TITLE
[5.10] Documentation - Typos & Consistency Fixes

### PR DESCRIPTION
**Pull request by patshaughnessy**
Cherry pick of #716 
- **Explanation**: Fixes some typos and formatting inconsistencies.
- **Scope**: Fixes spelling mistakes, mainly in comments. A typo in one enum case name was fixed, and the previous case spelling (with the typo) was deprecated. Also whitespace was removed.
- **GitHub Issue**: none.
- **Risk**: Low. No code was changed, aside from the one enum case that renamed.
- **Testing**: Ran the ./bin/test script and it succeeded
- **Reviewer**: @d-ronnqvist

### CODE REVIEW

**Comment by patshaughnessy** [comment]
@swift-ci please test

**Review by Kyle-Ye — APPROVED** [review]
LGTM. Update the title and body of this PR. Hope you don't mind

**Comment by Kyle-Ye** [comment]
Also would you mind update the commit message of the cherry pick commit? I do not have a force push permission for your fork. We usually use the original commit's commit message for the cherry-pick.

**Comment by patshaughnessy** [comment]
No problem. About the commit message: What would you like to see there? I included the original message "Documentation - Typos & Consistency Fixes" and I believe your name is still on the commit history since I used the cherry pick command. Do you just want to remove the "Cherry pick commit 7ddabfe:" text?

**Comment by Kyle-Ye** [comment]
> No problem. About the commit message: What would you like to see there? I included the original message "Documentation - Typos & Consistency Fixes" and I believe your name is still on the commit history since I used the cherry pick command. Do you just want to remove the "Cherry pick commit [7ddabfe](https://github.com/apple/swift-docc/commit/7ddabfece488a25525922a5ed08a75043604a9a4):" text?

Yes. Please keep the original message as it is.

```
Documentation - Typos & Consistency Fixes (#716)

Co-authored-by: Joey GM <joseph.gmk@gmail.com>
```

After you do "Squash and merge" in GitHub, the new PR number and your name will be automatically be added.
eg.
```
commit 71ec492359ec4edb5c783f150a179d2cb511f3e5 (tag: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-07-22-a)
Author: David Rönnqvist <ronnqvist@apple.com>
Date:   Wed Jul 12 11:24:38 2023 -0700

    Allow anchor <doc:#heading> within same article (#652) (#660)
    
    Co-authored-by: Natik Gadzhi <natik@respawn.io>
```

**Comment by patshaughnessy** [comment]
Ah now I remember why I changed the commit message. When I performed the cherry pick, git found merge conflicts and forced me to resolve them and create an entirely new commit. Most of the conflicts were whitespace in comments and a few code lines, I recall. I took the time to run the test suite to be sure I didn't break anything. All of this lead me to add that line to the commit message with the sha of the original commit, so we have that in the history.

If there weren't any conflicts the cherry pick command would have automatically preserved the original commit's sha and message.

Given all of this, the "Cherry pick commit ..." line in the message seems like a useful record of what happened here. If you still disagree I'm happy to take it out.

**Comment by Kyle-Ye** [comment]
Got it. I’m fine with the current status.

**Review by Kyle-Ye — APPROVED** [review]

**Review by franklinsch — APPROVED** [review]

**Comment by patshaughnessy** [comment]
@swift-ci please test

**Pull request merged**
