### PR TITLE
[5.7] Avoid using the module's customized display name when creating availability render items (#161)

### PR DESCRIPTION
**Pull request by d-ronnqvist**
- **Rationale:** This fixes a small issue where default availability items wasn't being rendered after customizing the module's display name.
- **Risk:** Low
- **Risk Detail:** This is a targeted change that only apply when the developer has customized the module's display name provided default availability for that module.
- **Reward:** Low
- **Reward Details:** The bug only happens when two relatively niche features are used together.
- **Original PR:** #161
- **Issue:** rdar://92197472
- **Code Reviewed By:** @ethan-kusters 
- **Testing Details:** Updated existing tests to verify that customizing the display name doesn't impact the availability items

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Review by franklinsch — APPROVED** [review]

**Pull request merged**
