### PR TITLE
Avoid appending coverage info concurrently.

### LINKED ISSUE #697: Non-deterministic failures without diagnostic
### Description

I get one of these errors every so often when running docc:

```
error: 'docc convert' invocation failed with a nonzero exit code: '6'
error: 'docc convert' invocation failed with a nonzero exit code: '11'
error: 'docc convert' invocation failed with a nonzero exit code: '64'
```

The command I'm using is:

```
        set -eo pipefail
        for TARGET in CLI Driver FrontEnd Core IR CodeGenLLVM Utils TestUtils HyloModule GenerateHyloFileTests; do
          mkdir -p _site/docc/"$TARGET"
          swift package --allow-writing-to-directory ./_site \
          generate-documentation \
          --target "$TARGET" \
          --output-path _site/docc/"$TARGET" \
          --experimental-documentation-coverage --level brief \
          --enable-inherited-docs \
          --transform-for-static-hosting \
          --hosting-base-path Hylo/docc/"$TARGET"
        done
```

I'm using it on [this project](https://github.com/hylo-lang/hyloc).  An example is [here](https://github.com/hylo-lang/hyloc/actions/runs/5885007273/job/15960726865?pr=836#step:9:622).

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Successful completion always.

### Actual behavior

_No response_

### Steps To Reproduce

With [this project](https://github.com/hylo-lang/hyloc), follow the README instructions for building, and then run the command I gave in my description.

### Swift-DocC Version Information

Whatever is installed with Xcode 14.3.1 I presume

### Swift Compiler Version Information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

### PR DESCRIPTION
**Pull request by d-ronnqvist**
**Explanation**: Fix a sporadic crash that occurs when the documentation coverage feature is enabled.
**Scope**: Appends coverage information to an array asynchronously, to avoid a race condition crash.
**GitHub Issue**: fixes #697 
**Risk**: Low. Small code change with no larger impact or risk.
**Testing**: Ran the ./bin/test script and it succeeded
**Reviewer**: @patshaughnessy 

Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/697 rdar://116872208

## Summary

This fixes a crash when using the experimental documentation coverage feature by not appending to the coverage info array  concurrently.

## Dependencies

None

## Testing

With the symbol graph files from https://github.com/apple/swift-docc/issues/697#issuecomment-1688624882, run this command repeatedly.
```
swift run docc convert --additional-symbol-graph-dir /path/to/extracted-symbols/hylo/Core \
  --experimental-documentation-coverage --level brief \
  --enable-inherited-docs 
```

Without these changes that command sometimes fails with one or more `malloc: double free for ptr 0x7fb390530000` errors.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
I didn't add tests to this PR, mainly because testing the lack of a data race and lack of an occasional crash can be awkward and slow.

**Review by Kyle-Ye — APPROVED** [review]
LGTM

**Comment by patshaughnessy** [comment]
Reading the test suite, it looks like we never actually call the line of code you modified here in any test:

```
coverageInfo.append(coverageEntry)
```

I updated one of the documentation coverage related unit tests, to:
- use a symbol graph file and not just an empty doc bundle so we have some coverage to report, and
- count the number of coverage structs reported, to be sure the `append` line above is actually called and working (even if there's no easy way to check for race conditions in a reliable way).

**Comment by patshaughnessy** [comment]
@swift-ci please test

**Review by patshaughnessy — APPROVED** [review]

**Comment by patshaughnessy** [comment]
@swift-ci please test

**Review by daniel-grumberg — APPROVED** [review]
LGTM

**Review by franklinsch — APPROVED** [review]

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
