### PR TITLE
Support cross compilation in macOS toolchain builds

### LINKED ISSUE #433: 5.8 nightlies ship x86 only docc binary
### Description

As described [here](https://forums.swift.org/t/support-for-docc-experimental-features/61276/6), the 5.8 nightlies ship a x86 only binary, which makes documentation generation fail on arm64 Macs without Rosetta.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

`docc` should be a universal binary.

### Actual behavior

_No response_

### Steps To Reproduce

_No response_

### Swift-DocC Version Information

_No response_

### Swift Compiler Version Information

_No response_

### PR DESCRIPTION
**Pull request by ethan-kusters**
Bug/issue #, if applicable: closes #433

## Summary

Updates the build script used in SwiftCI for building the `docc` executable as part of Swift.org toolchains to support cross compilation.

Currently the `docc` executable included in the otherwise universal macOS toolchain only supports x86_64. This resolves the issue.

### CODE REVIEW

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
The macOS toolchain attached to https://github.com/apple/swift/pull/62306 now includes a universal `docc` executable.

**Review by neonichu — APPROVED** [review]

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Review by shahmishal — APPROVED** [review]

**Review by d-ronnqvist — APPROVED** [review]

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Pull request merged**
