### PR TITLE
Update swift-markdown and fix test case

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

## Summary

Fix swift toolchain CI test case failing due to the swift-markdown breaking change PR.

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Review by eeckstein — APPROVED** [review]
lgtm

**Comment by sofiaromorales** [comment]
Did this change introduce the need for additional setup when building docc from source? @Kyle-Ye @eeckstein  

I'm getting this error when building swift-docc
```
error: 'swift-markdown': Couldn’t check out revision ‘e5ab90941a8415304b4a4e403253bd59fef00b5a’:
    fatal: reference is not a tree: e5ab90941a8415304b4a4e403253bd59fef00b5a
``

**Comment by Kyle-Ye** [comment]
> Did this change introduce the need for additional setup when building docc from source? @Kyle-Ye @eeckstein
> 
> I'm getting this error when building swift-docc
> 
> ```
> error: 'swift-markdown': Couldn’t check out revision ‘e5ab90941a8415304b4a4e403253bd59fef00b5a’:
>     fatal: reference is not a tree: e5ab90941a8415304b4a4e403253bd59fef00b5a
> ```

No. This seems to be Git issue to me.

e5ab90941a8415304b4a4e403253bd59fef00b5a is valid commit ID

See https://github.com/apple/swift-markdown/commit/e5ab90941a8415304b4a4e403253bd59fef00b5a

You may considering checking your network connection and fetch the latest swift-markdown GitHub origin again.

**Pull request merged**
