### PR TITLE
Remove deprecated path properties

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: none

## Summary

This removes the deprecated `path` properties on `LinkDestinationSummary` and `LinkDestinationSummary/Variant`. 

Doing this gets rid of a handful of deprecation warnings that add noise when running the tests. 

## Dependencies

n/a

## Testing

n/a

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- ~[ ] Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- ~[ ] Updated documentation if necessary~

### CODE REVIEW

**Review by franklinsch — APPROVED** [review]
thanks!

**Comment by Kyle-Ye** [comment]
Although this property is marked as deprecated, it's access level is public. Is this OK for us to break the public API in swift-docc from release/5.7 to release/5.8?

Is it acceptable if we do the same thing for swift-markdown and swift-docc-symbolkit when we are release a new Swift+1 version?

@franklinsch

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
> Although this property is marked as deprecated, it's access level is public. Is this OK for us to break the public API in swift-docc from release/5.7 to release/5.8?
> 
> Is it acceptable if we do the same thing for swift-markdown and swift-docc-symbolkit when we are release a new Swift+1 version?
> 
> @franklinsch

We should be looking at this on a case-by-case basis, but in general we should avoid API breaking changes as much as possible. I don't expect the `LinkDestinationSummary` API to be commonly used by clients, so the impact here wouldn't be large. However, another approach we could've opted for here is to remove only the call sites of these properties, and keep the deprecated property a little longer.

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
