### PR TITLE
Update default preview server port

### LINKED ISSUE #371: The default 8000 port may conflict with existing local web server ports.
### Feature Name

Change the default web port from 8000 to something else.

### Description

The default 8000 port may conflict with existing local web server ports.
Maybe there are other ports considerable like 114, 514, 1919, 810, 114514, etc.

### Motivation

_No response_

### Importance

The default 8000 port may conflict with existing local web server ports.

### Alternatives Considered

_No response_

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

Close #371 

Source: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http

Thanks @amartini51 for providing the source explanation

## Summary

Update default preview server port

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Review by franklinsch — APPROVED** [review]
Looks great, thanks!

**Comment by Kyle-Ye** [comment]
@swift-ci please test and merge

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Pull request merged**
